---
title: "Time series graphics"
output: rmarkdown::github_document
---

### ts objects
```{r}
y <- ts(c(123,39,78,52,110), start=2012)
y
```

### Time plots
```{r}
library(fpp)
library(forecast)
library(ggplot2)

class(melsyd)
head(melsyd)

autoplot(melsyd[, "Economy.Class"]) + ggtitle("Economy class passengers: Melbourne-Sydney") +
  xlab("Year") + ylab("in Thousands")
```


```{r}
head(a10, 10)
class(a10)

autoplot(a10) + ggtitle("Antidiabetic drug sales") +
  ylab("$ in million") + xlab("Year")
```

### Seasonal plots
```{r}
ggseasonplot(a10, year.labels = TRUE, year.labels.left = TRUE) + 
    ylab("$ million") + ggtitle("Seasonal plot: antidiabetic drug sales")
```

The data from each season are overlapped.


```{r}
ggseasonplot(a10, polar=TRUE) + ylab("$ million") + 
    ggtitle("Polar seasonal plot: antidiabetic drug sales")
```


### Seasonal subseries plots
```{r}
ggsubseriesplot(a10) + ylab("$ million") +
  ggtitle("Seasonal subseries plot: antidiabetic drug sales")
```


### Scatterplots
```{r}
library(fpp2)
head(elecdemand)

autoplot(elecdemand[,c("Demand","Temperature")], facets=TRUE) +
  xlab("Year: 2014") + ylab("") +
  ggtitle("Half-hourly electricity demand: Victoria, Australia")

qplot(Temperature, Demand, data = as.data.frame(elecdemand)) + 
  ylab("Demand (GW)") + xlab("Temperature (Celsius)")
```


```{r}
autoplot(visnights[,1:5], facets=TRUE) +
  ylab("Number of visitor nights each quarter (millions)")

GGally::ggpairs(as.data.frame(visnights[,1:5]))
```


```{r}
GGally::ggpairs(as.data.frame(visnights[,1:5]))
```

```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


